from __future__ import annotations

import json
import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    def load_dotenv() -> bool:
        return False


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = PROJECT_ROOT / "output"
TOPIC_FILE = OUTPUT_DIR / "topic.txt"
SCRIPT_FILE = OUTPUT_DIR / "script.txt"
SCRIPT_DATA_FILE = OUTPUT_DIR / "script_data.json"
UPLOAD_METADATA_FILE = OUTPUT_DIR / "upload_metadata.json"
YOUTUBE_CONFIG_FILE = OUTPUT_DIR / "youtube_config.json"
DEFAULT_TOPIC = "Roblox trending moments"
DEFAULT_SCRIPT = "Today we're counting down fun Roblox moments you need to see!"


def ensure_output_dir() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def to_bool(value: str) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def trim_text(value: str, max_length: int) -> str:
    value = value.strip()
    if len(value) <= max_length:
        return value
    return value[: max_length - 3].rstrip() + "..."


def unique_tags(values: list[str]) -> list[str]:
    seen = set()
    tags = []
    for value in values:
        clean_value = value.strip().lower()
        if not clean_value or clean_value in seen:
            continue
        seen.add(clean_value)
        tags.append(clean_value)
    return tags


def read_topic() -> str:
    if not TOPIC_FILE.exists():
        print(f"[upload_youtube] Missing output/topic.txt. Using fallback topic: {DEFAULT_TOPIC}")
        return DEFAULT_TOPIC

    topic = TOPIC_FILE.read_text(encoding="utf-8").strip()
    return topic or DEFAULT_TOPIC


def read_script() -> str:
    if not SCRIPT_FILE.exists():
        print("[upload_youtube] Missing output/script.txt. Using fallback script text.")
        return DEFAULT_SCRIPT

    script_text = SCRIPT_FILE.read_text(encoding="utf-8").strip()
    return script_text or DEFAULT_SCRIPT


def read_script_data(topic: str) -> dict:
    if not SCRIPT_DATA_FILE.exists():
        print("[upload_youtube] Missing output/script_data.json. Using fallback script data.")
        return {
            "topic": topic,
            "intro": DEFAULT_SCRIPT,
            "ranked_items": [],
            "cta": "Comment your number one pick and follow for more kid-friendly Shorts!",
        }

    try:
        return json.loads(SCRIPT_DATA_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        print("[upload_youtube] Invalid script_data.json. Using fallback script data.")
        return {
            "topic": topic,
            "intro": DEFAULT_SCRIPT,
            "ranked_items": [],
            "cta": "Comment your number one pick and follow for more kid-friendly Shorts!",
        }


def build_title(topic: str) -> str:
    return trim_text(f"Top 5 Picks for {topic} #shorts", 95)


def build_description(topic: str, script_data: dict, script_text: str) -> str:
    intro = script_data.get("intro", "").strip()
    ranked_items = script_data.get("ranked_items", [])
    cta = script_data.get("cta", "").strip()

    lines = [
        intro or script_text.splitlines()[0].strip(),
        "",
        f"Topic: {topic}",
    ]

    if ranked_items:
        lines.append("Highlights:")
        for item in ranked_items:
            lines.append(f"- {item}")

    if cta:
        lines.extend(["", cta])

    lines.extend(
        [
            "",
            "Kids-friendly Shorts metadata generated by Kids Shorts Factory.",
            "#shorts #roblox #kids",
        ]
    )
    return "\n".join(lines).strip()


def build_tags(topic: str, ranked_items: list[str]) -> list[str]:
    topic_bits = topic.replace("-", " ").split()
    ranked_bits = []
    for item in ranked_items[:5]:
        ranked_bits.extend(item.replace("-", " ").split()[:2])

    raw_tags = [
        "shorts",
        "kids",
        "roblox",
        "brookhaven",
        "adopt me",
        "rainbow friends",
        "99 nights",
        "memes",
        "animations",
        topic,
        *topic_bits,
        *ranked_bits,
    ]
    return unique_tags(raw_tags)[:15]


def build_upload_metadata(topic: str, script_data: dict, script_text: str) -> dict:
    load_dotenv()
    upload_enabled = to_bool(os.getenv("UPLOAD_TO_YOUTUBE", "false"))
    ranked_items = script_data.get("ranked_items", [])

    return {
        "title": build_title(topic),
        "description": build_description(topic, script_data, script_text),
        "tags": build_tags(topic, ranked_items),
        "upload_enabled": upload_enabled,
    }


def build_youtube_config(upload_enabled: bool) -> dict:
    load_dotenv()
    client_id = os.getenv("YOUTUBE_CLIENT_ID", "").strip()
    client_secret = os.getenv("YOUTUBE_CLIENT_SECRET", "").strip()
    return {
        "upload_enabled": upload_enabled,
        "client_id_present": bool(client_id),
        "client_secret_present": bool(client_secret),
        "api_mode": "placeholder",
        "note": "Real YouTube API upload is still a TODO.",
    }


def save_upload_metadata(metadata: dict) -> Path:
    ensure_output_dir()
    UPLOAD_METADATA_FILE.write_text(
        json.dumps(metadata, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"[upload_youtube] Saved upload metadata to {UPLOAD_METADATA_FILE.relative_to(PROJECT_ROOT)}")
    return UPLOAD_METADATA_FILE


def save_youtube_config(youtube_config: dict) -> Path:
    ensure_output_dir()
    YOUTUBE_CONFIG_FILE.write_text(
        json.dumps(youtube_config, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"[upload_youtube] Saved YouTube config to {YOUTUBE_CONFIG_FILE.relative_to(PROJECT_ROOT)}")
    return YOUTUBE_CONFIG_FILE


def main() -> dict:
    topic = read_topic()
    script_text = read_script()
    script_data = read_script_data(topic)
    upload_metadata = build_upload_metadata(topic, script_data, script_text)
    youtube_config = build_youtube_config(upload_metadata["upload_enabled"])

    save_upload_metadata(upload_metadata)
    save_youtube_config(youtube_config)

    # TODO: Add real YouTube Data API upload logic here when cloud auth and
    # upload handling are ready.
    if not upload_metadata["upload_enabled"]:
        print("[upload_youtube] UPLOAD_TO_YOUTUBE is false. Metadata saved and upload skipped.")
    elif not youtube_config["client_id_present"] or not youtube_config["client_secret_present"]:
        print("[upload_youtube] Upload requested but credentials are missing. Skipping real upload.")
    else:
        print("[upload_youtube] Upload is enabled, but real YouTube upload is still a TODO.")

    return upload_metadata


if __name__ == "__main__":
    main()
